# i3blocks configuration file
#
# The i3blocks man page describes the usage of the binary,
# and its website describes the configuration:
#
#     https://vivien.github.io/i3blocks


# Global properties
separator=true
separator_block_width=15


# Blocks
[startpadding]
color=#b4b4b4
command=echo "  "
interval=once

#[network6]
#color=#b4b4b4
#command= X=$(ip -6 addr show dev wlp2s0 | grep inet6); Y=$(echo $X | cut -d' ' -f2); echo IPv6: $Y
#interval=16

[network4]
color=#b4b4b4
command= X=$(ip -4 addr show dev wlp2s0 | grep inet); Y=$(echo $X | cut -d' ' -f2); echo IPv4: $Y
interval=16

[memory]
color=#b4b4b4
command= X=$(cat /proc/meminfo | grep -i "MemTotal" | cut -d ":" -f2 | tr -d "kB" | xargs); Y=$(cat /proc/meminfo | grep -i "MemFree" | cut -d ":" -f2 | tr -d "kB" | xargs); Z=$(expr $X - $Y); Z=$(expr $Z / 1024); X=$(expr $X / 1024); echo RAM: $Z"Mb/"$X"Mb" 
interval=4

[temp]
color=#b4b4b4
command= X=$(cat /sys/class/thermal/thermal_zone2/temp); Y=$(expr $X / 1000); echo TEMP: $Y"C"
interval=8

[battery]
color=#b4b4b4
command=echo "BAT: $(X=$(cat /sys/class/power_supply/BAT0/uevent | grep POWER_SUPPLY_ENERGY_FULL= | cut -d "=" -f2); Y=$(cat /sys/class/power_supply/BAT0/uevent | grep POWER_SUPPLY_ENERGY_NOW= | cut -d "=" -f2); Y=$(expr $Y \* 100); expr $Y / $X)%" 
interval=8

[charging]
color=#b4b4b4
command= X=$(cat /sys/class/power_supply/ADP1/online); echo CHRG: $X
interval=8

[time]
color=#b4b4b4
command=date '+%d/%m/%Y %H:%M:%S'
interval=1

[endpadding]
color=#b4b4b4
command=echo "  "
interval=once
