#! /bin/sh

# TODO: add feh wallpaper with `feh --bg-scale <path/to/wallpaper>`

# start sxhkd
pgrep -x sxhkd > /dev/null || sxhkd &

# start feh
feh --no-fehbg --bg-fill /usr/local/share/theme/wallpaper/desert.png

# workspaces
bspc monitor -d A B C D E F
#bspc config top_patting 30

# tiles
bspc config split_ratio         0.50
bspc config swallow_first_click false

# borders
bspc config border_width  6
bspc config window_gap   16

# theme
bspc config focused_border_color  "#101010"
bspc config active_border_color   "#000000"
bspc config normal_border_color   "#000000"
bspc config presel_feedback_color "#B3A12F"

# example exceptions
#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off

# start polybar
polybar &
